# https://taskfile.dev

version: '3'

vars:
  GOOS: linux
  GOARCH: arm64
  GOARM: 
  BINDIR: bin/play

tasks:

  build:
    silent: true
    cmds:
      - echo "Building..."
      - rm -rf {{.BINPLAY}}
      - env GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} go build -o {{.BINDIR}}

  send:
    silent: true
    cmds:
      - echo "Sending to client..."
      - sftp mdes@192.168.1.151:/home/mdes/ <<< $'put {{.BINDIR}}'

  all:
    siletn: true
    cmds:
    - task build
    - task send

  default:
    cmds:
      - echo ":o"
    silent: true
